name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@1faaf50aa09d5793d9a100819973df801febfb31 # v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
          files: |
            dist/**/*
            LICENSE
            README.md
            action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
